### ISSUE TITLE
pip install xdress

### ISSUE THREAD

**Issue by rhl-** [xdress/xdress#269]
$ sudo pip install xdress
 Disabling clang since llvm-config not found: tried llvm-config, llvm-config-3.5, llvm-config-3.4, llvm-config-3.3, llvm-config-3.2
    To override, set the LLVM_CONFIG environment variable.
    changing mode of build/scripts-2.7/xdress from 644 to 755
and then:
$ xdress --debug
autoall: discovering API names
autoall: no API names to discover!
autodescribe: registering simplex
autodescribe: registering cube
WARNING: RuntimeWarning: cython does not seem to be installed
dtypes: registering numpy dtypes
stlwrap: registering C++ standard library types
autodescribe: scraping C/C++ APIs from source
autodescribe: describing simplex
Traceback (most recent call last):
  File "/usr/bin/xdress", line 6, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/xdress/main.py", line 222, in main
    plugins.execute()
  File "/usr/lib/python2.7/site-packages/xdress/plugins.py", line 374, in execute
    self.exit(e)
  File "/usr/lib/python2.7/site-packages/xdress/plugins.py", line 372, in execute
    plugin.execute(rc)
  File "/usr/lib/python2.7/site-packages/xdress/autodescribe.py", line 2284, in execute
    self.compute_classes(rc)
  File "/usr/lib/python2.7/site-packages/xdress/autodescribe.py", line 2451, in compute_classes
    desc = self.compute_desc(cls, 'class', rc)
  File "/usr/lib/python2.7/site-packages/xdress/autodescribe.py", line 2371, in compute_desc
    clang_includes=rc.clang_includes)
  File "/usr/lib/python2.7/site-packages/xdress/autodescribe.py", line 2225, in describe
    parser = astparsers.pick_parser(language, parsers)
  File "/usr/lib/python2.7/site-packages/xdress/astparsers.py", line 357, in pick_parser
    raise RuntimeError(msg)
RuntimeError: C++ parsers not available: c, c++

The same exact behavior occurs on linux and os/x.

Can you please outline a clear way to install xdress, without having to perhaps reinstall clang on my mac.. ?

This seems very useful for me, as I write highly templated C++ and I want cython bindings..

**Comment by lewismc** [comment]
Hi @rhl- I am struggling to get running with xdress as well on MacOSX Mavericks.
I see you getting two issues here
```
WARNING: RuntimeWarning: cython does not seem to be installed
```
and then, what I am getting
```
RuntimeError: C++ parsers not available: c, c++
```
I'm not aware of how to define the C parser on the CLI

**Comment by scopatz** [comment]
I think if you pass in `-p` or `--parsers` you can set the parser on the command line.

**Comment by lewismc** [comment]
@rhl- @scopatz if you look at what @rhl- has typed above
```
xdress --debug
```
The behavior is correct. If you want to check for xdress being properly installed then you can simply run 
```
xdress --help
```
or
```
xdress --version
```
The latter is useful to see if you have additional (some optional) dependencies installed. For example when I do this (I am using master branch from GH) I get the following
```
lmcgibbn@LMC-032857 /usr/local/jpl/snow/trunk/tmscag/trunk(master) $ xdress --version
XDress: 0.5-dev
pycparser (optional): 2.13
lxml (optional): 3.4.2
NumPy (optional): 1.6.2
Cython (optional): 0.21.1
```
I don't think this is an issue... I would suggest that this issue can be closed off.

**Comment by scopatz** [comment]
If @rhl- feels comfortable closing it :)

**Comment by rhl-** [comment]
I will close it if you guys will tell me how to get things running! I realize it may be pedantically correct, but, why is pip install xdress not properly installing xdress, in the sense that clearly from the message, things are not installed that it cares about.

**Comment by lewismc** [comment]
Can you try

Xdress --help

On Wednesday, May 13, 2015, Ryan H. Lewis <notifications@github.com> wrote:

> I will close it if you guys will tell me how to get things running! I
> realize it may be pedantically correct, but, why is pip install xdress not
> properly installing xdress, in the sense that clearly from the message,
> things are not installed that it cares about.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xdress/xdress/issues/269#issuecomment-101900518>.
>


-- 
*Lewis*

**Comment by rhl-** [comment]
sure, it works:
$ xdress --help
usage: Generates XDress API [-h] [--rc RC] [--plugins PLUGINS [PLUGINS ...]]
                            [--debug] [-v] [--version] [--dumpdesc]
                            [--package PACKAGE] [--packagedir PACKAGEDIR]
                            [--sourcedir SOURCEDIR] [--builddir BUILDDIR]
                            [--bash-completion] [--no-bash-completion]
                            [--dtypes-module DTYPES_MODULE]
                            [--stlcontainers-module STLCONTAINERS_MODULE]
                            [-I INCLUDES [INCLUDES ...]]
                            [-D DEFINES [DEFINES ...]]
                            [-U UNDEFINES [UNDEFINES ...]] [-p PARSERS]
                            [--clear-parser-cache-period CLEAR_PARSER_CACHE_PERIOD]
                            [--dumpast FILE]
                            [--clang-includes CLANG_INCLUDES [CLANG_INCLUDES ...]]
                            [--extra-parser-args EXTRA_PARSER_ARGS [EXTRA_PARSER_ARGS ...]]
                            [--max-callbacks MAX_CALLBACKS]
                            [--extra-types EXTRA_TYPES] [--make-extra-types]
                            [--no-make-extra-types] [--make-dtypes]
                            [--no-make-dtypes] [--make-stlcontainers]
                            [--no-make-stlcontainers]

optional arguments:
  -h, --help            show this help message and exit
  --rc RC               Path to run control file
  --plugins PLUGINS [PLUGINS ...]
                        Plugins to include
  --debug               Build in debugging mode
  -v, --verbose         Print more output.
  --version             Print version information.
  --dumpdesc            Print the description cache
  --package PACKAGE     The Python package name for the generated wrappers
  --packagedir PACKAGEDIR
                        Path to package directory, same as 'package' if not
                        specified
  --sourcedir SOURCEDIR
                        Path to source directory (deprecated)
  --builddir BUILDDIR   Path to build directory
  --bash-completion     enable bash completion
  --no-bash-completion  disable bash completion
  --dtypes-module DTYPES_MODULE
                        Module name for numpy dtype wrappers.
  --stlcontainers-module STLCONTAINERS_MODULE
                        Module name for C++ standard library container
                        wrappers.
  -I INCLUDES [INCLUDES ...], --includes INCLUDES [INCLUDES ...]
                        Additional include directories
  -D DEFINES [DEFINES ...], --defines DEFINES [DEFINES ...]
                        Set additional macro definitions
  -U UNDEFINES [UNDEFINES ...], --undefines UNDEFINES [UNDEFINES ...]
                        Unset additional macro definitions
  -p PARSERS            Parser(s) name, list, or dict
  --clear-parser-cache-period CLEAR_PARSER_CACHE_PERIOD
                        Number of parser calls to perform before clearing the
                        internal cache. This prevents nasty memory overflow
                        issues.
  --dumpast FILE        Prints the abstract syntax tree of a file.
  --clang-includes CLANG_INCLUDES [CLANG_INCLUDES ...]
                        clang-specific include paths
  --extra-parser-args EXTRA_PARSER_ARGS [EXTRA_PARSER_ARGS ...]
                        Further command line arguments to pass to the parser
  --max-callbacks MAX_CALLBACKS
                        The maximum number of callbacks for function pointers
  --extra-types EXTRA_TYPES
                        Module and header file name for xdress extra types.
  --make-extra-types    make extra types wrapper
  --no-make-extra-types
                        don't make extra types wrapper
  --make-dtypes         make numpy dtype wrappers
  --no-make-dtypes      don't make numpy dtype wrappers
  --make-stlcontainers  make C++ STL container wrappers
  --no-make-stlcontainers
                        don't make C++ STL container wrappers

**Comment by lewismc** [comment]
That looks ok to me.
I'm noticing that some dependencies are not optional as described! Is this
your issue?

On Wednesday, May 13, 2015, Ryan H. Lewis <notifications@github.com> wrote:

> sure, it works:
> $ xdress --help
> usage: Generates XDress API [-h] [--rc RC] [--plugins PLUGINS [PLUGINS
> ...]]
> [--debug] [-v] [--version] [--dumpdesc]
> [--package PACKAGE] [--packagedir PACKAGEDIR]
> [--sourcedir SOURCEDIR] [--builddir BUILDDIR]
> [--bash-completion] [--no-bash-completion]
> [--dtypes-module DTYPES_MODULE]
> [--stlcontainers-module STLCONTAINERS_MODULE]
> [-I INCLUDES [INCLUDES ...]]
> [-D DEFINES [DEFINES ...]]
> [-U UNDEFINES [UNDEFINES ...]] [-p PARSERS]
> [--clear-parser-cache-period CLEAR_PARSER_CACHE_PERIOD]
> [--dumpast FILE]
> [--clang-includes CLANG_INCLUDES [CLANG_INCLUDES ...]]
> [--extra-parser-args EXTRA_PARSER_ARGS [EXTRA_PARSER_ARGS ...]]
> [--max-callbacks MAX_CALLBACKS]
> [--extra-types EXTRA_TYPES] [--make-extra-types]
> [--no-make-extra-types] [--make-dtypes]
> [--no-make-dtypes] [--make-stlcontainers]
> [--no-make-stlcontainers]
>
> optional arguments:
> -h, --help show this help message and exit
> --rc RC Path to run control file
> --plugins PLUGINS [PLUGINS ...]
> Plugins to include
> --debug Build in debugging mode
> -v, --verbose Print more output.
> --version Print version information.
> --dumpdesc Print the description cache
> --package PACKAGE The Python package name for the generated wrappers
> --packagedir PACKAGEDIR
> Path to package directory, same as 'package' if not
> specified
> --sourcedir SOURCEDIR
> Path to source directory (deprecated)
> --builddir BUILDDIR Path to build directory
> --bash-completion enable bash completion
> --no-bash-completion disable bash completion
> --dtypes-module DTYPES_MODULE
> Module name for numpy dtype wrappers.
> --stlcontainers-module STLCONTAINERS_MODULE
> Module name for C++ standard library container
> wrappers.
> -I INCLUDES [INCLUDES ...], --includes INCLUDES [INCLUDES ...]
> Additional include directories
> -D DEFINES [DEFINES ...], --defines DEFINES [DEFINES ...]
> Set additional macro definitions
> -U UNDEFINES [UNDEFINES ...], --undefines UNDEFINES [UNDEFINES ...]
> Unset additional macro definitions
> -p PARSERS Parser(s) name, list, or dict
> --clear-parser-cache-period CLEAR_PARSER_CACHE_PERIOD
> Number of parser calls to perform before clearing the
> internal cache. This prevents nasty memory overflow
> issues.
> --dumpast FILE Prints the abstract syntax tree of a file.
> --clang-includes CLANG_INCLUDES [CLANG_INCLUDES ...]
> clang-specific include paths
> --extra-parser-args EXTRA_PARSER_ARGS [EXTRA_PARSER_ARGS ...]
> Further command line arguments to pass to the parser
> --max-callbacks MAX_CALLBACKS
> The maximum number of callbacks for function pointers
> --extra-types EXTRA_TYPES
> Module and header file name for xdress extra types.
> --make-extra-types make extra types wrapper
> --no-make-extra-types
> don't make extra types wrapper
> --make-dtypes make numpy dtype wrappers
> --no-make-dtypes don't make numpy dtype wrappers
> --make-stlcontainers make C++ STL container wrappers
> --no-make-stlcontainers
> don't make C++ STL container wrappers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xdress/xdress/issues/269#issuecomment-101900749>.
>


-- 
*Lewis*

**Comment by rhl-** [comment]
I just reinstalled xdress by the way to do this. It seems to have changed since I actually filed the bug. I will close it since now I see:

$ xdress --debug
no package name given; please add 'package' to xdressrc.py

**Comment by rhl-** [comment]
I guess its unclear where xdressrc.py lives but, that is perhaps a different issue.

**Comment by rhl-** [comment]
Concretely the issue I was raising is that I get: RuntimeError: C++ parsers not available: c, c++

And I have no idea why they were not available, where they are, how to get them, etc.. I wasn't at the time of bug filing, finding the answers.

**Comment by lewismc** [comment]
So I've been using xdress with xdressrc.py at the top level directory of my
project. Header files etc are then referenced from within the file in a
local context.
There is documentation in this on the project website (not GH README)
Hth

On Wednesday, May 13, 2015, Ryan H. Lewis <notifications@github.com> wrote:

> I guess its unclear where xdressrc.py lives but, that is perhaps a
> different issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xdress/xdress/issues/269#issuecomment-101901814>.
>


-- 
*Lewis*

**Comment by lewismc** [comment]
I understand and I was also having an issue recently with understanding
which parsers were available.
In master there was only today a patch merged for making it explicit that
you can use clang, gccxml and pycparser (not sure if the final one is the
correct name off the top of my head).
Hopethully this will help us in the future.
Lewis

On Wednesday, May 13, 2015, Ryan H. Lewis <notifications@github.com> wrote:

> Concretely the issue I was raising is that I get: RuntimeError: C++
> parsers not available: c, c++
>
> And I have no idea why they were not available, where they are, how to get
> them, etc.. I wasn't at the time of bug filing, finding the answers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xdress/xdress/issues/269#issuecomment-101902470>.
>


-- 
*Lewis*
