### ISSUE TITLE
Explicitly mention available parsers upon Errors and on CLI

### ISSUE THREAD

**Issue by lewismc** [xdress/xdress#272]
I was lost and had to dog in to the code when I was introduced to the '-p' argument for main().
This improvement provides some more informative CLI help as well as better Exception when a suitable parser cannot be located.

**Comment by lewismc** [comment]
Final aspect of this commit can be found over on https://github.com/xdress/xdress/pull/274

**Comment by lewismc** [comment]
@scopatz it is good to commit. Once you are happy to merge please close off both 272 and 274

**Comment by scopatz** [comment]
Thanks
